apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realidadstore-cicd-workspace
  namespace: cicd
  labels:
    app.kubernetes.io/name: realidadstore
    app.kubernetes.io/component: cicd-workspace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
