apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: realidadstore-build-
  namespace: cicd
  labels:
    app.kubernetes.io/name: realidadstore
    app.kubernetes.io/component: image-build
spec:
  pipelineRef:
    name: realidadstore-ci

  taskRunTemplate:
    serviceAccountName: realidadstore-pipeline

  params:
    - name: git-url
      value: "https://github.com/AngelUri03/realidadstore-devops.git"

    - name: git-revision
      value: "main"

    - name: image-namespace
      value: "angeluri"

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: realidadstore-cicd-workspace

    - name: dockerconfig
      secret:
        secretName: dockerhub-config
