apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: realidadstore
  labels:
    app: frontend
    app.kubernetes.io/name: realidadstore
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: realidadstore
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/angeluri/realidadstore-frontend:775d1a3b11380715753f4da9d5fa2c13777cefac
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
